import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Footer from '../components/Footer'
import NavBar from '../components/NavBar'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bell Ripper</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to the Bell Ripper Secure Document Portal!
        </h1>

        <p className={styles.description}>
          Legal Documents delivered, managed, signed. Securely.
        </p>

        <div className={styles.grid}>
          <a href="http://www.bellripper.com/mediation.html" className={styles.card}>
            <h2>Mediation &rarr;</h2>
            <p>​Mediation is a process to find solutions uniquely tailored to your situation</p>
          </a>

          <a href="http://www.bellripper.com/lifeandestateplanning.html" className={styles.card}>
            <h2>Life and Estate Planning &rarr;</h2>
            <p>Legal Documents to prepare, plan, and manage your Life and Estate</p>
          </a>

          <a
            href="http://www.bellripper.com/resources.html"
            className={styles.card}
          >
            <h2>Resources &rarr;</h2>
            <p>An extensive list of resources for Bexar County Families</p>
          </a>

          <a
            href="http://www.bellripper.com/aboutus.html"
            className={styles.card}
          >
            <h2>About Us &rarr;</h2>
            <p>
              Get to know the Bell Ripper team! Read our bio's, view contact details 
            </p>
          </a>
        </div>
      </main>
      <Footer/>
      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}

export default Home
